version: '3'
services:
  app:
    build:
      context: .
    ports:
      - "5000"
    volumes:
      - .:/GAMETAGYT
    environment:
      - SQLALCHEMY_DATABASE_URI=mysql+pymysql://root:ovidiu@db:3306/mydb
    depends_on:
      db:
        condition: service_healthy


  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: ovidiu
      MYSQL_DATABASE: mydb
    ports:
      - "3333:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - app
    ports:
      - "80:80"
